# Generated by Django 3.2.5 on 2021-10-30 15:21

from django.db import migrations, models
import djrichtextfield.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Development',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=164)),
                ('job_company', models.CharField(max_length=164)),
                ('location', models.CharField(max_length=164)),
                ('description', djrichtextfield.models.RichTextField(blank=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('hidden', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Driving',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=164)),
                ('job_company', models.CharField(max_length=164)),
                ('location', models.CharField(max_length=164)),
                ('description', djrichtextfield.models.RichTextField(blank=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('hidden', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Nursing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=164)),
                ('job_company', models.CharField(max_length=164)),
                ('location', models.CharField(max_length=164)),
                ('description', djrichtextfield.models.RichTextField(blank=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('hidden', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Welding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=164)),
                ('job_company', models.CharField(max_length=164)),
                ('location', models.CharField(max_length=164)),
                ('description', djrichtextfield.models.RichTextField(blank=True)),
                ('last_update', models.DateTimeField(auto_now=True)),
                ('hidden', models.BooleanField(default=False)),
                ('slug', models.SlugField(blank=True, max_length=500, unique=True)),
            ],
        ),
    ]
